<?php

return [
    'websites' => [
        'AlpinTrek' => [
            'https://www.alpinetrek.co.uk/climbing-shoes',
            'https://www.alpinetrek.co.uk/carabiners-quickdraws',
            'https://www.alpinetrek.co.uk/climbing-harnesses',
            'https://www.alpinetrek.co.uk/climbing-ropes',
            'https://www.alpinetrek.co.uk/climbing-boulder-accessories',
            'https://www.alpinetrek.co.uk/slings-cord',
            'https://www.alpinetrek.co.uk/belay-devices-descenders',
            'https://www.alpinetrek.co.uk/climbing-helmets',
            'https://www.alpinetrek.co.uk/climbing-bouldering-training',
            'https://www.alpinetrek.co.uk/mountaineering-ice-climbing',
            'https://www.alpinetrek.co.uk/bigwall-trad-climbing',
            'https://www.alpinetrek.co.uk/via-ferrata-gear',
            'https://www.alpinetrek.co.uk/crash-pads',
            'https://www.alpinetrek.co.uk/climbing-sets',
            'https://www.alpinetrek.co.uk/slacklining',
        ],
        'BananaFingers' => [
            '',
        ],
        'ClimbersShop' => [
            'https://www.climbers-shop.com/climbing-equipment/ascenders--descenders-and-pulleys',
            'https://www.climbers-shop.com/climbing-equipment/big-wall-gear',
            'https://www.climbers-shop.com/climbing-equipment/climbing-cams',
            'https://www.climbers-shop.com/climbing-equipment/climbing-shoes',
            'https://www.climbers-shop.com/climbing-equipment/non-locking-carabiners',
            'https://www.climbers-shop.com/climbing-equipment/pulleys',
            'https://www.climbers-shop.com/climbing-equipment/climbing-ropes',
            'https://www.climbers-shop.com/climbing-equipment/skin-care',
            'https://www.climbers-shop.com/climbing-equipment/belay-devices',
            'https://www.climbers-shop.com/climbing-equipment/bouldering-and-training',
            'https://www.climbers-shop.com/climbing-equipment/climbing-harnesses',
            'https://www.climbers-shop.com/climbing-equipment/connectors',
            'https://www.climbers-shop.com/climbing-equipment/nut-keys',
            'https://www.climbers-shop.com/climbing-equipment/quickdraws',
            'https://www.climbers-shop.com/climbing-equipment/slings',
            'https://www.climbers-shop.com/climbing-equipment/beta-sticks',
            'https://www.climbers-shop.com/climbing-equipment/chalk-and-chalkbags',
            'https://www.climbers-shop.com/climbing-equipment/climbing-helmets',
            'https://www.climbers-shop.com/climbing-equipment/locking-carabiners',
            'https://www.climbers-shop.com/climbing-equipment/nuts-and-hexes',
            'https://www.climbers-shop.com/climbing-equipment/rope-bags',
            'https://www.climbers-shop.com/climbing-equipment/via-ferrata-sets',
        ],
        'CotswoldOutdoor' => [
            'https://www.cotswoldoutdoor.com/c/climbing/climbing-shoes.html',
            'https://www.cotswoldoutdoor.com/c/climbing/climbing-harnesses.html',
            'https://www.cotswoldoutdoor.com/c/climbing/ropes.html?page=0',
            'https://www.cotswoldoutdoor.com/c/climbing/ropes.html?page=1',
            'https://www.cotswoldoutdoor.com/c/climbing/ropes.html?page=2',
            'https://www.cotswoldoutdoor.com/c/climbing/ropes.html?page=3',
            'https://www.cotswoldoutdoor.com/c/climbing/climbing-helmets.html',
            'https://www.cotswoldoutdoor.com/c/climbing/chalk-bouldering-training.html',
            'https://www.cotswoldoutdoor.com/c/climbing/belay-abseil-ascent.html',
            'https://www.cotswoldoutdoor.com/c/climbing/climbing-protection.html',
            'https://www.cotswoldoutdoor.com/c/climbing/carabiners-quickdraws.html',
            'https://www.cotswoldoutdoor.com/c/climbing/ice-axes-crampons.html',
            'https://www.cotswoldoutdoor.com/c/climbing/climbing-slings.html',
        ],
        'Decathlon' => [
            'https://www.decathlon.co.uk/C-881836-climbing-shoes',
            'https://www.decathlon.co.uk/C-535605-carabiners-and-quickdraws',
            'https://www.decathlon.co.uk/C-881837-climbing-harnesses',
            'https://www.decathlon.co.uk/C-541994-climbing-ropes-and-ropes-bags/N-299827-product-type~climbing-rope',
            'https://www.decathlon.co.uk/C-541994-climbing-ropes-and-ropes-bags/N-299827-product-type~sling',
            'https://www.decathlon.co.uk/C-541994-climbing-ropes-and-ropes-bags/N-299827-product-type~climbing-accessory-cord',
            'https://www.decathlon.co.uk/C-541994-climbing-ropes-and-ropes-bags/N-299827-product-type~static-rope',
            'https://www.decathlon.co.uk/C-541994-climbing-ropes-and-ropes-bags/N-299827-product-type~climbing-bag',
            'https://www.decathlon.co.uk/C-541994-climbing-ropes-and-ropes-bags/N-299827-product-type~climbing-lanyard',
            'https://www.decathlon.co.uk/C-869316-chalk-bags-chalk-and-accessories',
            'https://www.decathlon.co.uk/C-869273-climbing-clothing/N-328037-gender~women',
            'https://www.decathlon.co.uk/C-869273-climbing-clothing/N-328037-gender~men',
            'https://www.decathlon.co.uk/C-869273-climbing-clothing/N-328037-gender~boys',
            'https://www.decathlon.co.uk/C-869273-climbing-clothing/N-328037-gender~girls',
            'https://www.decathlon.co.uk/C-869317-belay-devices-camming-devices-and-nuts',
            'https://www.decathlon.co.uk/C-869270-climbing-helmets',
            'https://www.decathlon.co.uk/C-1125268-climbing-holds',
        ],
        'DicksClimbing' => [
            '',
        ],
        'EllisBrigham' => [
            '',
        ],
        'GoOutdoors' => [
            '',
        ],
        'RockRun' => [
            //Climbing Hardware
            'https://rockrun.com/collections/aid-gear',
            'https://rockrun.com/collections/ascenders',
            'https://rockrun.com/collections/belay-devices',
            'https://rockrun.com/collections/carabiners',
            'https://rockrun.com/collections/climbing-cams',
            'https://rockrun.com/collections/climbing-shoes',
            'https://rockrun.com/collections/deal',
            'https://rockrun.com/collections/descenders',
            'https://rockrun.com/collections/hex',
            'https://rockrun.com/collections/maillons',
            'https://rockrun.com/collections/micro-nut',
            'https://rockrun.com/collections/nut-keys',
            'https://rockrun.com/collections/nut',
            'https://rockrun.com/collections/pegs',
            'https://rockrun.com/collections/pulleys',
            'https://rockrun.com/collections/quickdraws',
            'https://rockrun.com/collections/tri-cams',
//            //Ropes & Slings
            'https://rockrun.com/collections/accessory-cord-and-tape',
            'https://rockrun.com/collections/gear-sling',
            'https://rockrun.com/collections/climbing-ropes',
            'https://rockrun.com/collections/confidence-ropes',
            'https://rockrun.com/collections/daisy-chains',
            'https://rockrun.com/collections/lanyards',
            'https://rockrun.com/collections/rope-bags',
            'https://rockrun.com/collections/rope-hooks',
            'https://rockrun.com/collections/rope-protectors',
            'https://rockrun.com/collections/static-rope',
            'https://rockrun.com/collections/shock-absorbers',
            'https://rockrun.com/collections/slings',
//            //Climbing Shoes
            'https://rockrun.com/collections/climbing-shoes',
            'https://rockrun.com/collections/kids-rock-shoes',
            'https://rockrun.com/collections/womens-rock-shoes',
//            //Climbing Harnesses
            'https://rockrun.com/collections/harnesses',
            'https://rockrun.com/collections/kids-harnesses',
            'https://rockrun.com/collections/womens-harnesses',
//            //Via Ferrata
            'https://rockrun.com/collections/via-ferrata-kits',
            'https://rockrun.com/collections/via-ferrata',
//            //Climbing Essentials
            'https://rockrun.com/collections/belay-glasses',
            'https://rockrun.com/collections/belay-gloves',
            'https://rockrun.com/collections/climbing-chalk',
            'https://rockrun.com/collections/climbing-equipment-cleaning-and-maintenance',
            'https://rockrun.com/collections/clip-sticks',
            'https://rockrun.com/collections/chalk-bags',
            'https://rockrun.com/collections/crack-climbing-gloves',
            'https://rockrun.com/collections/finger-tape',
            'https://rockrun.com/collections/hand-repair-and-skin-care',
            'https://rockrun.com/collections/helmets',
            'https://rockrun.com/collections/knives',
            'https://rockrun.com/collections/outdoor-first-aid-kits',
            'https://rockrun.com/collections/rucksacks',
//            //Bouldering & Training
            'https://rockrun.com/collections/bouldering-pads',
            'https://rockrun.com/collections/climbing-brushes',
            'https://rockrun.com/collections/campus-rungs',
            'https://rockrun.com/collections/climbing-holds',
            'https://rockrun.com/collections/fingerboards',
            'https://rockrun.com/collections/training-aids',
        ],
        'TheClimbingDepot' => [
            '',
        ],
        'TrekkInn' => [ // TODO: problem with pagination - not all equipments are loading/scraped...
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A%22Beal%22',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Petzl%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Salewa%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Black%20diamond%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Mammut%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Grivel%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Ocun%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Singing%20rock%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Wildcountry%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Climbing%20technology%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Kong%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Qi%C2%B4roc%22)',

//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A(14518)&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Petzl%22+OR+%22Salewa%22+OR+%22La%20sportiva%22+OR+%22Black%20diamond%22+OR+%22Grivel%22+OR+%22Mammut%22+OR+%22Ocun%22+OR+%22Beal%22+OR+%22Singing%20rock%22+OR+%22Wildcountry%22+OR+%22Climbing%20technology%22+OR+%228%20b%20plus%22+OR+%22Snap%20climbing%22+OR+%22Lifeventure%22+OR+%228%20c%20plus%22+OR+%22Ultimate%20performance%22+OR+%22Kong%22)',

            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-accessories/14518/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-ascenders---descenders/14525/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-belay-devices/14516/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-carabiners/14515/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-chalk-bags/14388/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-friends-nuts---pitons/14524/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-harnesses/14513/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-lanyards---energy-absorbers/14522/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-pulleys/14520/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-rope-bags-and-gear/14593/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-ropes---webbing/14514/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-sets/14521/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-slacklines/11427/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-wall-equipment/14523/s',
        ],
    ],
];
