<?php

return [
    'websites' => [
        'AlpinTrek' => [
            'https://www.alpinetrek.co.uk/climbing-shoes',
            'https://www.alpinetrek.co.uk/carabiners-quickdraws',
            'https://www.alpinetrek.co.uk/climbing-harnesses',
            'https://www.alpinetrek.co.uk/climbing-ropes',
            'https://www.alpinetrek.co.uk/climbing-boulder-accessories',
            'https://www.alpinetrek.co.uk/slings-cord',
            'https://www.alpinetrek.co.uk/belay-devices-descenders',
            'https://www.alpinetrek.co.uk/climbing-helmets',
            'https://www.alpinetrek.co.uk/climbing-bouldering-training',
            'https://www.alpinetrek.co.uk/mountaineering-ice-climbing',
            'https://www.alpinetrek.co.uk/bigwall-trad-climbing',
            'https://www.alpinetrek.co.uk/via-ferrata-gear',
            'https://www.alpinetrek.co.uk/crash-pads',
            'https://www.alpinetrek.co.uk/climbing-sets',
            'https://www.alpinetrek.co.uk/slacklining',
        ],
        'BananaFingers' => [
            //accessory-cord
            'https://www.bananafingers.co.uk/category/accessory-cord',
            //ascenders
            'https://www.bananafingers.co.uk/category/ascenders',
            //belays
            'https://www.bananafingers.co.uk/category/belays',
            //big-wall
            'https://www.bananafingers.co.uk/category/aiders-etriers',
            'https://www.bananafingers.co.uk/category/big-wall-hardware',
            'https://www.bananafingers.co.uk/category/daisy-chains-0',
            'https://www.bananafingers.co.uk/category/haul-bags',
            'https://www.bananafingers.co.uk/category/pitons-pegs',
            'https://www.bananafingers.co.uk/category/portaledges-and-flies',
            //books-guides
            'https://www.bananafingers.co.uk/category/climbing-books',
            'https://www.bananafingers.co.uk/category/climbing-guides',
            'https://www.bananafingers.co.uk/category/europe',
            'https://www.bananafingers.co.uk/category/uk-south',
            'https://www.bananafingers.co.uk/category/uk-wales',
            'https://www.bananafingers.co.uk/category/everywhere',
            'https://www.bananafingers.co.uk/category/uk-scotland',
            'https://www.bananafingers.co.uk/category/france-font',
            'https://www.bananafingers.co.uk/category/uk-peak-district',
            'https://www.bananafingers.co.uk/category/uk-england-north',
            'https://www.bananafingers.co.uk/category/uk-england-west',
            'https://www.bananafingers.co.uk/category/rest-world',
            //boulder-pads
            'https://www.bananafingers.co.uk/category/boulder-pads',
            //cams-friends
            'https://www.bananafingers.co.uk/category/dmm-dragonfly',
            'https://www.bananafingers.co.uk/category/alien-cams',
            'https://www.bananafingers.co.uk/category/wild-country-friends',
            'https://www.bananafingers.co.uk/category/totem-cams',
            'https://www.bananafingers.co.uk/category/metolius-tcu',
            'https://www.bananafingers.co.uk/category/metolious-ultralight-master-cam',
            'https://www.bananafingers.co.uk/category/dmm-dragon-cams',
            'https://www.bananafingers.co.uk/category/dmm-demon-cams',
            'https://www.bananafingers.co.uk/category/camp-tricams',
            'https://www.bananafingers.co.uk/category/black-diamond-camalot-x4-offset',
            'https://www.bananafingers.co.uk/category/black-diamond-camalot-x4',
            'https://www.bananafingers.co.uk/category/black-diamond-camalot-ultralight',
            'https://www.bananafingers.co.uk/category/black-diamond-camalot-c4',
            //camping
//            'https://www.bananafingers.co.uk/category/tents',
//            'https://www.bananafingers.co.uk/category/bivi-bags',
//            'https://www.bananafingers.co.uk/category/tent-accessories',
//            'https://www.bananafingers.co.uk/category/backpacking-tents',
//            'https://www.bananafingers.co.uk/category/sleeping-bags',
//            'https://www.bananafingers.co.uk/category/down-sleeping-bags',
//            'https://www.bananafingers.co.uk/category/sleeping-bag-liners',
//            'https://www.bananafingers.co.uk/category/synthetic-sleeping-bags',
//            'https://www.bananafingers.co.uk/category/sleeping-mats',
//            'https://www.bananafingers.co.uk/category/insulated-sleeping-mats',
//            'https://www.bananafingers.co.uk/category/air-sleeping-mats',
//            'https://www.bananafingers.co.uk/category/foam-roll-sleeping-mats',
//            'https://www.bananafingers.co.uk/category/camping-pillows',
//            'https://www.bananafingers.co.uk/category/cooking-eating',
//            'https://www.bananafingers.co.uk/category/camping-stoves',
//            'https://www.bananafingers.co.uk/category/camping-cooking-sets',
//            'https://www.bananafingers.co.uk/category/camping-plates-bowls',
//            'https://www.bananafingers.co.uk/category/camping-pots-pans',
//            'https://www.bananafingers.co.uk/category/camping-cups-mugs',
//            'https://www.bananafingers.co.uk/category/camping-cutlery',
//            'https://www.bananafingers.co.uk/category/camping-coffee-makers',
//            'https://www.bananafingers.co.uk/category/food-storage',
//            'https://www.bananafingers.co.uk/category/hydration',
//            'https://www.bananafingers.co.uk/category/thermos-flasks',
//            'https://www.bananafingers.co.uk/category/water-bottles',
//            'https://www.bananafingers.co.uk/category/water-filters',
//            'https://www.bananafingers.co.uk/category/hammocks',
//            'https://www.bananafingers.co.uk/category/camping-accessories',
//            'https://www.bananafingers.co.uk/category/camping-showers',
//            'https://www.bananafingers.co.uk/category/camping-towels',
//            'https://www.bananafingers.co.uk/category/dry-bags',
//            'https://www.bananafingers.co.uk/category/headlamps-torches',
            //carabiners
            'https://www.bananafingers.co.uk/category/carabiners',
            //chalk-accessories
            'https://www.bananafingers.co.uk/category/chalk-accessories',
            //chalk-bags
            'https://www.bananafingers.co.uk/category/chalk-bags',
            //climbing-holds
            'https://www.bananafingers.co.uk/category/climbing-holds',
            //mens-clothing
            'https://www.bananafingers.co.uk/category/baselayers',
            'https://www.bananafingers.co.uk/category/beanies',
            'https://www.bananafingers.co.uk/category/caps',
            'https://www.bananafingers.co.uk/category/gloves',
            'https://www.bananafingers.co.uk/category/hoodies',
            'https://www.bananafingers.co.uk/category/jackets',
            'https://www.bananafingers.co.uk/category/shirts',
            'https://www.bananafingers.co.uk/category/shorts-34',
            'https://www.bananafingers.co.uk/category/t-shirts',
            'https://www.bananafingers.co.uk/category/tops',
            'https://www.bananafingers.co.uk/category/trousers',
            'https://www.bananafingers.co.uk/category/underwear',
            'https://www.bananafingers.co.uk/category/vests',
            //womens-clothing
            'https://www.bananafingers.co.uk/category/pants',
            'https://www.bananafingers.co.uk/category/vests-0',
            'https://www.bananafingers.co.uk/category/skirtsdresses',
            'https://www.bananafingers.co.uk/category/shorts-34-0',
            'https://www.bananafingers.co.uk/category/long-sleeve-tops',
            'https://www.bananafingers.co.uk/category/leggings',
            'https://www.bananafingers.co.uk/category/jackets-0',
            'https://www.bananafingers.co.uk/category/gloves-0',
            'https://www.bananafingers.co.uk/category/bra-tops',
            'https://www.bananafingers.co.uk/category/beanieshats',
            'https://www.bananafingers.co.uk/category/baselayers-0',
            'https://www.bananafingers.co.uk/category/bags',
            'https://www.bananafingers.co.uk/category/t-shirts-0',
            //childrens-clothing-0
            'https://www.bananafingers.co.uk/category/childrens-clothing-0',
            //descenders
            'https://www.bananafingers.co.uk/category/descenders',
            //footwear
            'https://www.bananafingers.co.uk/category/slippers',
            'https://www.bananafingers.co.uk/category/mountain-boots',
            'https://www.bananafingers.co.uk/category/climbing-shoes',
            'https://www.bananafingers.co.uk/category/approach-shoes',
            'https://www.bananafingers.co.uk/category/accessories',
            //gear-slings
            'https://www.bananafingers.co.uk/category/gear-slings',
            //hangboards-training
            'https://www.bananafingers.co.uk/category/hangboards-training',
            //harnesses
            'https://www.bananafingers.co.uk/category/harnesses',
            //helmets
            'https://www.bananafingers.co.uk/category/helmets',
            //head-torches
            'https://www.bananafingers.co.uk/category/head-torches',
            //ice-climbing
            'https://www.bananafingers.co.uk/category/accessories-0',
            'https://www.bananafingers.co.uk/category/snow-anchors',
            'https://www.bananafingers.co.uk/category/leashes',
            'https://www.bananafingers.co.uk/category/ice-screws',
            'https://www.bananafingers.co.uk/category/ice-axes-piolets',
            'https://www.bananafingers.co.uk/category/crampons',
            'https://www.bananafingers.co.uk/category/pitons-pegs-0',
            //nut-keys
            'https://www.bananafingers.co.uk/category/nut-keys',
            //pulleys
            'https://www.bananafingers.co.uk/category/pulleys',
            //quickdraws
            'https://www.bananafingers.co.uk/category/quickdraws',
            //rocks-nuts
            'https://www.bananafingers.co.uk/category/dmm-torque-nuts',
            'https://www.bananafingers.co.uk/category/trango-ballnutz',
            'https://www.bananafingers.co.uk/category/metolius-ultralight-curve-nuts',
            'https://www.bananafingers.co.uk/category/dmm-wallnuts',
            'https://www.bananafingers.co.uk/category/dmm-wallnut-micros',
            'https://www.bananafingers.co.uk/category/dmm-peenuts',
            'https://www.bananafingers.co.uk/category/wild-country-rocks-wire',
            'https://www.bananafingers.co.uk/category/dmm-offset-nuts',
            'https://www.bananafingers.co.uk/category/dmm-brass-offsets',
            'https://www.bananafingers.co.uk/category/dmm-brass-imp',
            'https://www.bananafingers.co.uk/category/camp-ball-nuts',
            'https://www.bananafingers.co.uk/category/black-diamond-stoppers',
            'https://www.bananafingers.co.uk/category/black-diamond-offset-stoppers',
            'https://www.bananafingers.co.uk/category/wild-country-rockcentrics',
            'https://www.bananafingers.co.uk/category/wild-country-superlight-offset',
            'https://www.bananafingers.co.uk/category/black-diamond-hexcentrics',
            'https://www.bananafingers.co.uk/category/wild-country-superlight-rocks',
            'https://www.bananafingers.co.uk/category/black-diamond-micro-stoppers',
            'https://www.bananafingers.co.uk/category/black-diamond-offset-micros',
            //rope-bags
            'https://www.bananafingers.co.uk/category/rope-bags',
            //ropes
            'https://www.bananafingers.co.uk/category/ropes',
            //rucksacks
            'https://www.bananafingers.co.uk/category/rucksacks',
            //slacklines
            'https://www.bananafingers.co.uk/category/slacklines',
            //slings
            'https://www.bananafingers.co.uk/category/tech-webbing',
            'https://www.bananafingers.co.uk/category/quickdraw-slings',
            'https://www.bananafingers.co.uk/category/nylon-slings',
            'https://www.bananafingers.co.uk/category/lanyards',
            'https://www.bananafingers.co.uk/category/dyneema-slings',
            'https://www.bananafingers.co.uk/category/daisy-chains',
            'https://www.bananafingers.co.uk/category/belay-stations',
            'https://www.bananafingers.co.uk/category/aramid-slings',
            'https://www.bananafingers.co.uk/category/trekking-poles',
            //ferrata
            'https://www.bananafingers.co.uk/category/carabiners-0',
            'https://www.bananafingers.co.uk/category/lanyards-0',
        ],
        'ClimbersShop' => [
            'https://www.climbers-shop.com/climbing-equipment/ascenders--descenders-and-pulleys',
            'https://www.climbers-shop.com/climbing-equipment/big-wall-gear',
            'https://www.climbers-shop.com/climbing-equipment/climbing-cams',
            'https://www.climbers-shop.com/climbing-equipment/climbing-shoes',
            'https://www.climbers-shop.com/climbing-equipment/non-locking-carabiners',
            'https://www.climbers-shop.com/climbing-equipment/pulleys',
            'https://www.climbers-shop.com/climbing-equipment/climbing-ropes',
            'https://www.climbers-shop.com/climbing-equipment/skin-care',
            'https://www.climbers-shop.com/climbing-equipment/belay-devices',
            'https://www.climbers-shop.com/climbing-equipment/bouldering-and-training',
            'https://www.climbers-shop.com/climbing-equipment/climbing-harnesses',
            'https://www.climbers-shop.com/climbing-equipment/connectors',
            'https://www.climbers-shop.com/climbing-equipment/nut-keys',
            'https://www.climbers-shop.com/climbing-equipment/quickdraws',
            'https://www.climbers-shop.com/climbing-equipment/slings',
            'https://www.climbers-shop.com/climbing-equipment/beta-sticks',
            'https://www.climbers-shop.com/climbing-equipment/chalk-and-chalkbags',
            'https://www.climbers-shop.com/climbing-equipment/climbing-helmets',
            'https://www.climbers-shop.com/climbing-equipment/locking-carabiners',
            'https://www.climbers-shop.com/climbing-equipment/nuts-and-hexes',
            'https://www.climbers-shop.com/climbing-equipment/rope-bags',
            'https://www.climbers-shop.com/climbing-equipment/via-ferrata-sets',
        ],
        'CotswoldOutdoor' => [
            'https://www.cotswoldoutdoor.com/c/climbing/climbing-shoes.html',
            'https://www.cotswoldoutdoor.com/c/climbing/climbing-harnesses.html',
            'https://www.cotswoldoutdoor.com/c/climbing/ropes.html?page=0',
            'https://www.cotswoldoutdoor.com/c/climbing/ropes.html?page=1',
            'https://www.cotswoldoutdoor.com/c/climbing/ropes.html?page=2',
            'https://www.cotswoldoutdoor.com/c/climbing/ropes.html?page=3',
            'https://www.cotswoldoutdoor.com/c/climbing/climbing-helmets.html',
            'https://www.cotswoldoutdoor.com/c/climbing/chalk-bouldering-training.html',
            'https://www.cotswoldoutdoor.com/c/climbing/belay-abseil-ascent.html',
            'https://www.cotswoldoutdoor.com/c/climbing/climbing-protection.html',
            'https://www.cotswoldoutdoor.com/c/climbing/carabiners-quickdraws.html',
            'https://www.cotswoldoutdoor.com/c/climbing/ice-axes-crampons.html',
            'https://www.cotswoldoutdoor.com/c/climbing/climbing-slings.html',
        ],
        'Decathlon' => [
            'https://www.decathlon.co.uk/C-881836-climbing-shoes',
            'https://www.decathlon.co.uk/C-535605-carabiners-and-quickdraws',
            'https://www.decathlon.co.uk/C-881837-climbing-harnesses',
            'https://www.decathlon.co.uk/C-541994-climbing-ropes-and-ropes-bags/N-299827-product-type~climbing-rope',
            'https://www.decathlon.co.uk/C-541994-climbing-ropes-and-ropes-bags/N-299827-product-type~sling',
            'https://www.decathlon.co.uk/C-541994-climbing-ropes-and-ropes-bags/N-299827-product-type~climbing-accessory-cord',
            'https://www.decathlon.co.uk/C-541994-climbing-ropes-and-ropes-bags/N-299827-product-type~static-rope',
            'https://www.decathlon.co.uk/C-541994-climbing-ropes-and-ropes-bags/N-299827-product-type~climbing-bag',
            'https://www.decathlon.co.uk/C-541994-climbing-ropes-and-ropes-bags/N-299827-product-type~climbing-lanyard',
            'https://www.decathlon.co.uk/C-869316-chalk-bags-chalk-and-accessories',
            'https://www.decathlon.co.uk/C-869273-climbing-clothing/N-328037-gender~women',
            'https://www.decathlon.co.uk/C-869273-climbing-clothing/N-328037-gender~men',
            'https://www.decathlon.co.uk/C-869273-climbing-clothing/N-328037-gender~boys',
            'https://www.decathlon.co.uk/C-869273-climbing-clothing/N-328037-gender~girls',
            'https://www.decathlon.co.uk/C-869317-belay-devices-camming-devices-and-nuts',
            'https://www.decathlon.co.uk/C-869270-climbing-helmets',
            'https://www.decathlon.co.uk/C-1125268-climbing-holds',
        ],
        'DicksClimbing' => [
            '',
        ],
        'EllisBrigham' => [
            'https://www.ellis-brigham.com/climbing-accessories',
            'https://www.ellis-brigham.com/ice-climbing-equipment',
            'https://www.ellis-brigham.com/climbing-equipment',
            'https://www.ellis-brigham.com/kids-climbing-shoes',
            'https://www.ellis-brigham.com/womens-climbing-shoes',
            'https://www.ellis-brigham.com/mens-climbing-shoes',
            'https://www.ellis-brigham.com/womens-climbing-clothing',
            'https://www.ellis-brigham.com/mens-climbing-clothing',
        ],
        'GoOutdoors' => [
            'https://www.gooutdoors.co.uk/climbing/climbing-helmets/?items_per_page=10000',
            'https://www.gooutdoors.co.uk/climbing/camming-devices/?items_per_page=10000',
            'https://www.gooutdoors.co.uk/climbing/climbing-packs/?items_per_page=10000',
            'https://www.gooutdoors.co.uk/climbing/climbing-holds-and-training/?items_per_page=10000',
            'https://www.gooutdoors.co.uk/climbing/climbing-slings/?items_per_page=10000',
            'https://www.gooutdoors.co.uk/climbing/approach-shoes/?items_per_page=10000',
            'https://www.gooutdoors.co.uk/climbing/winter-climbing/?items_per_page=10000',
            'https://www.gooutdoors.co.uk/climbing/climbing-harnesses/?items_per_page=10000',
            'https://www.gooutdoors.co.uk/climbing/climbing-shoes/?items_per_page=10000',
            'https://www.gooutdoors.co.uk/climbing/climbing-clothing/?items_per_page=10000',
            'https://www.gooutdoors.co.uk/climbing/carabiners/?items_per_page=10000',
            'https://www.gooutdoors.co.uk/climbing/bouldering-mats-and-brushes/?items_per_page=10000',
            'https://www.gooutdoors.co.uk/climbing/chalk-and-chalk-bags/?items_per_page=10000',
            'https://www.gooutdoors.co.uk/climbing/climbing-ropes/?items_per_page=10000',
            'https://www.gooutdoors.co.uk/climbing/belay-devices-and-descenders/?items_per_page=10000',
            'https://www.gooutdoors.co.uk/climbing/nuts-rocks-and-hexes/?items_per_page=10000',
            'https://www.gooutdoors.co.uk/climbing/ropebags/?items_per_page=10000',
            'https://www.gooutdoors.co.uk/climbing/via-ferrata/?items_per_page=10000',
        ],
        'RockRun' => [
            //Climbing Hardware
            'https://rockrun.com/collections/aid-gear',
            'https://rockrun.com/collections/ascenders',
            'https://rockrun.com/collections/belay-devices',
            'https://rockrun.com/collections/carabiners',
            'https://rockrun.com/collections/climbing-cams',
            'https://rockrun.com/collections/climbing-shoes',
            'https://rockrun.com/collections/deal',
            'https://rockrun.com/collections/descenders',
            'https://rockrun.com/collections/hex',
            'https://rockrun.com/collections/maillons',
            'https://rockrun.com/collections/micro-nut',
            'https://rockrun.com/collections/nut-keys',
            'https://rockrun.com/collections/nut',
            'https://rockrun.com/collections/pegs',
            'https://rockrun.com/collections/pulleys',
            'https://rockrun.com/collections/quickdraws',
            'https://rockrun.com/collections/tri-cams',
//            //Ropes & Slings
            'https://rockrun.com/collections/accessory-cord-and-tape',
            'https://rockrun.com/collections/gear-sling',
            'https://rockrun.com/collections/climbing-ropes',
            'https://rockrun.com/collections/confidence-ropes',
            'https://rockrun.com/collections/daisy-chains',
            'https://rockrun.com/collections/lanyards',
            'https://rockrun.com/collections/rope-bags',
            'https://rockrun.com/collections/rope-hooks',
            'https://rockrun.com/collections/rope-protectors',
            'https://rockrun.com/collections/static-rope',
            'https://rockrun.com/collections/shock-absorbers',
            'https://rockrun.com/collections/slings',
//            //Climbing Shoes
            'https://rockrun.com/collections/climbing-shoes',
            'https://rockrun.com/collections/kids-rock-shoes',
            'https://rockrun.com/collections/womens-rock-shoes',
//            //Climbing Harnesses
            'https://rockrun.com/collections/harnesses',
            'https://rockrun.com/collections/kids-harnesses',
            'https://rockrun.com/collections/womens-harnesses',
//            //Via Ferrata
            'https://rockrun.com/collections/via-ferrata-kits',
            'https://rockrun.com/collections/via-ferrata',
//            //Climbing Essentials
            'https://rockrun.com/collections/belay-glasses',
            'https://rockrun.com/collections/belay-gloves',
            'https://rockrun.com/collections/climbing-chalk',
            'https://rockrun.com/collections/climbing-equipment-cleaning-and-maintenance',
            'https://rockrun.com/collections/clip-sticks',
            'https://rockrun.com/collections/chalk-bags',
            'https://rockrun.com/collections/crack-climbing-gloves',
            'https://rockrun.com/collections/finger-tape',
            'https://rockrun.com/collections/hand-repair-and-skin-care',
            'https://rockrun.com/collections/helmets',
            'https://rockrun.com/collections/knives',
            'https://rockrun.com/collections/outdoor-first-aid-kits',
            'https://rockrun.com/collections/rucksacks',
//            //Bouldering & Training
            'https://rockrun.com/collections/bouldering-pads',
            'https://rockrun.com/collections/climbing-brushes',
            'https://rockrun.com/collections/campus-rungs',
            'https://rockrun.com/collections/climbing-holds',
            'https://rockrun.com/collections/fingerboards',
            'https://rockrun.com/collections/training-aids',
        ],
        'TheClimbingDepot' => [
            '',
        ],
        'TrekkInn' => [ // TODO: problem with pagination - not all equipments are loading/scraped...
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A%22Beal%22',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Petzl%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Salewa%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Black%20diamond%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Mammut%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Grivel%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Ocun%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Singing%20rock%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Wildcountry%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Climbing%20technology%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Kong%22)',
//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A14517&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Qi%C2%B4roc%22)',

//            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s#fq=id_familia%3A11243&fq={!tag=ds}id_subfamilia%3A(14518)&fq=id_tienda%3A3&sort=v30+desc,product(tm3,%20dispo)+asc&start=0&fq={!tag=dm}marca%3A(%22Petzl%22+OR+%22Salewa%22+OR+%22La%20sportiva%22+OR+%22Black%20diamond%22+OR+%22Grivel%22+OR+%22Mammut%22+OR+%22Ocun%22+OR+%22Beal%22+OR+%22Singing%20rock%22+OR+%22Wildcountry%22+OR+%22Climbing%20technology%22+OR+%228%20b%20plus%22+OR+%22Snap%20climbing%22+OR+%22Lifeventure%22+OR+%228%20c%20plus%22+OR+%22Ultimate%20performance%22+OR+%22Kong%22)',

            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-accessories/14518/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-ascenders---descenders/14525/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-belay-devices/14516/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-carabiners/14515/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-chalk-bags/14388/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-friends-nuts---pitons/14524/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-harnesses/14513/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-lanyards---energy-absorbers/14522/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-pulleys/14520/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-quickdraws/14517/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-rope-bags-and-gear/14593/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-ropes---webbing/14514/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-sets/14521/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-slacklines/11427/s',
            'https://www.trekkinn.com/outdoor-mountain/climbing-equipment-wall-equipment/14523/s',
        ],
    ],
];
